version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_DB: 'my_database'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis-upstash:
    image: redis/redis-stack:latest
    container_name: redis_upstash_local
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      REDIS_ARGS: '--requirepass password123'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
